# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 202)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.line_a_att = QtWidgets.QLineEdit(self.centralwidget)
        self.line_a_att.setObjectName("line_a_att")
        self.gridLayout.addWidget(self.line_a_att, 2, 0, 1, 1)
        self.coordCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.coordCheck.setObjectName("coordCheck")
        self.gridLayout.addWidget(self.coordCheck, 6, 0, 1, 1)
        self.press = QtWidgets.QPushButton(self.centralwidget)
        self.press.setObjectName("press")
        self.gridLayout.addWidget(self.press, 10, 0, 1, 1)
        self.autoParam = QtWidgets.QCheckBox(self.centralwidget)
        self.autoParam.setObjectName("autoParam")
        self.gridLayout.addWidget(self.autoParam, 1, 0, 1, 1)
        self.line_k_res = QtWidgets.QLineEdit(self.centralwidget)
        self.line_k_res.setMinimumSize(QtCore.QSize(620, 22))
        self.line_k_res.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_k_res.setObjectName("line_k_res")
        self.gridLayout.addWidget(self.line_k_res, 3, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 7, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "APF"))
        self.line_a_att.setText(_translate("MainWindow", "введите параметр a"))
        self.coordCheck.setText(_translate("MainWindow", "auto координаты"))
        self.press.setText(_translate("MainWindow", "Запуск скрипта"))
        self.autoParam.setText(_translate("MainWindow", "auto параметры"))
        self.line_k_res.setText(_translate("MainWindow", "введите параметр k"))
        self.lineEdit.setText(_translate("MainWindow", "Прим: 3 4, 14 54, 23 34"))
        self.actionsave.setText(_translate("MainWindow", "save"))
