# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.press = QtWidgets.QPushButton(self.centralwidget)
        self.press.setGeometry(QtCore.QRect(180, 400, 411, 91))
        self.press.setObjectName("press")
        self.line_k_res = QtWidgets.QLineEdit(self.centralwidget)
        self.line_k_res.setGeometry(QtCore.QRect(390, 250, 181, 71))
        self.line_k_res.setObjectName("line_k_res")
        self.line_a_att = QtWidgets.QLineEdit(self.centralwidget)
        self.line_a_att.setGeometry(QtCore.QRect(600, 250, 181, 71))
        self.line_a_att.setObjectName("line_a_att")
        self.autoCoordinates = QtWidgets.QRadioButton(self.centralwidget)
        self.autoCoordinates.setGeometry(QtCore.QRect(20, 10, 131, 51))
        self.autoCoordinates.setObjectName("autoCoordinates")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(340, 520, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.defaultParams = QtWidgets.QRadioButton(self.centralwidget)
        self.defaultParams.setGeometry(QtCore.QRect(390, 190, 131, 51))
        self.defaultParams.setObjectName("defaultParams")
        self.autosize_100 = QtWidgets.QRadioButton(self.centralwidget)
        self.autosize_100.setGeometry(QtCore.QRect(570, 80, 131, 51))
        self.autosize_100.setObjectName("autosize_100")
        self.autosize_50 = QtWidgets.QRadioButton(self.centralwidget)
        self.autosize_50.setGeometry(QtCore.QRect(500, 80, 131, 51))
        self.autosize_50.setObjectName("autosize_50")
        self.autosize_10 = QtWidgets.QRadioButton(self.centralwidget)
        self.autosize_10.setGeometry(QtCore.QRect(410, 80, 131, 51))
        self.autosize_10.setObjectName("autosize_10")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 90, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.press.setText(_translate("MainWindow", "Запуск скрипта"))
        self.line_k_res.setText(_translate("MainWindow", "введите параметр k"))
        self.line_a_att.setText(_translate("MainWindow", "введите параметр a"))
        self.autoCoordinates.setText(_translate("MainWindow", "auto"))
        self.defaultParams.setText(_translate("MainWindow", "auto params"))
        self.autosize_100.setText(_translate("MainWindow", "100x100"))
        self.autosize_50.setText(_translate("MainWindow", "50x50"))
        self.autosize_10.setText(_translate("MainWindow", "10x10"))
        self.actionsave.setText(_translate("MainWindow", "save"))
