# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QVBoxLayout


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.press = QtWidgets.QPushButton(self.centralwidget)
        self.press.setGeometry(QtCore.QRect(590, 530, 191, 51))
        self.press.setObjectName("press")
        self.line_k_res = QtWidgets.QLineEdit(self.centralwidget)
        self.line_k_res.setGeometry(QtCore.QRect(20, 380, 131, 51))
        self.line_k_res.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_k_res.setObjectName("line_k_res")
        self.line_a_att = QtWidgets.QLineEdit(self.centralwidget)
        self.line_a_att.setGeometry(QtCore.QRect(170, 380, 131, 51))
        self.line_a_att.setObjectName("line_a_att")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 550, 551, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 230, 281, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.coordCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.coordCheck.setGeometry(QtCore.QRect(20, 190, 131, 20))
        self.coordCheck.setObjectName("coordCheck")
        self.autoParam = QtWidgets.QCheckBox(self.centralwidget)
        self.autoParam.setGeometry(QtCore.QRect(20, 340, 81, 20))
        self.autoParam.setObjectName("autoParam")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.press.setText(_translate("MainWindow", "Запуск скрипта"))
        self.line_k_res.setText(_translate("MainWindow", "введите параметр k"))
        self.line_a_att.setText(_translate("MainWindow", "введите параметр a"))
        self.lineEdit.setText(_translate("MainWindow", "Прим: 3 4 14 54 23 34"))
        self.coordCheck.setText(_translate("MainWindow", "auto координаты"))
        self.autoParam.setText(_translate("MainWindow", "auto"))
        self.actionsave.setText(_translate("MainWindow", "save"))
