# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.press = QtWidgets.QPushButton(self.centralwidget)
        self.press.setGeometry(QtCore.QRect(180, 460, 411, 91))
        self.press.setObjectName("press")
        self.line_k_res = QtWidgets.QLineEdit(self.centralwidget)
        self.line_k_res.setGeometry(QtCore.QRect(70, 320, 181, 71))
        self.line_k_res.setObjectName("line_k_res")
        self.line_a_att = QtWidgets.QLineEdit(self.centralwidget)
        self.line_a_att.setGeometry(QtCore.QRect(290, 320, 181, 71))
        self.line_a_att.setObjectName("line_a_att")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(90, 260, 91, 21))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuedit = QtWidgets.QMenu(self.menuBar)
        self.menuedit.setObjectName("menuedit")
        MainWindow.setMenuBar(self.menuBar)
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.menuedit.addAction(self.actionsave)
        self.menuBar.addAction(self.menuedit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.press.setText(_translate("MainWindow", "Запуск скрипта"))
        self.menuedit.setTitle(_translate("MainWindow", "edit"))
        self.actionsave.setText(_translate("MainWindow", "save"))
